version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9
    working_directory: ~/creature-features
    steps:
      - checkout

      - run: npm install
      - run: npm run lint
      - run: npm run build
      # run tests!
      - run: npm test
      - run: npm run coverage
      - run:
          name: Setup Github
          command: |
            git config --global user.email "Kevnz@users.noreply.github.com"
            git config --global user.name "Kevin Isom"
            echo "machine github.com login Kevnz password $GITHUB_TOKEN" > ~/.netrc
      - run: npm run publish:site
