version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/forms
    steps:
      - checkout

      - run: npm install
      - run: npm run build
      # run tests!
      - run: npm test
      - run: npm run coverage
      - run: npm run test:ci
      - store_test_results:
          path: ~/forms/reports
